### ISSUE TITLE
It works on 460.91.03 and older version but not on latest version like 510.73.05

### ISSUE THREAD

**Issue by Danny87Chew** [LulaSvob/overclock-nvidia-ubuntu-linux#1]
It works fine on 460.91.03 and older version but not on latest version like 510.73.05.
"/usr/bin/nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=$ACTUAL_MEMORY_OFFSET" does not work on 510.73.05.
It reports error of  " ERROR: Error assigning value 2800 to attribute 'GPUMemoryTransferRateOffsetAllPerformanceLevels' (HOSTNAME:0[gpu:0]) as specified in assignment
       '[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=2800' (Unknown Error).  "

The good thing is that "Set Power Limit" still works fine.
sudo nvidia-smi -pl $POWER_LIMIT

**Comment by LulaSvob** [comment]
Here is the solution: https://askubuntu.com/questions/1407882/cant-manage-video-card-with-nvidia-drivers-version-510-on-ubuntu-22-04-lts

It's not the properties that do not work but this happens because Xorg is not running in root mode. 

Let me know if it worked on your side so I can close the issue. 
I also updated the readme.

**Comment by Danny87Chew** [comment]
Thanks a lot. It works fine as you suggested. 
Sorry for the later response as I was offline these days.
